enum Gen09PokemonProfiles {
    static let all: [PokemonProfile] = [
        PokemonProfiles.sprigatito, PokemonProfiles.floragato, PokemonProfiles.meowscarada, PokemonProfiles.fuecoco,
        PokemonProfiles.crocalor, PokemonProfiles.skeledirge, PokemonProfiles.quaxly, PokemonProfiles.quaxwell,
        PokemonProfiles.quaquaval, PokemonProfiles.lechonk, PokemonProfiles.oinkologne, PokemonProfiles.femaleOinkologne,
        PokemonProfiles.dudunsparce, PokemonProfiles.threeSegmentDudunsparce, PokemonProfiles.tarountula, PokemonProfiles.spidops,
        PokemonProfiles.nymble, PokemonProfiles.lokix, PokemonProfiles.rellor, PokemonProfiles.rabsca,
        PokemonProfiles.greavard, PokemonProfiles.houndstone, PokemonProfiles.flittle, PokemonProfiles.espathra,
        PokemonProfiles.farigiraf, PokemonProfiles.wiglett, PokemonProfiles.wugtrio, PokemonProfiles.dondozo,
        PokemonProfiles.veluza, PokemonProfiles.finizen, PokemonProfiles.palafin, PokemonProfiles.heroPalafin,
        PokemonProfiles.smoliv, PokemonProfiles.dolliv, PokemonProfiles.arboliva, PokemonProfiles.capsakid,
        PokemonProfiles.scovillain, PokemonProfiles.megaScovillain, PokemonProfiles.tadbulb, PokemonProfiles.bellibolt,
        PokemonProfiles.varoom, PokemonProfiles.revavroom, PokemonProfiles.orthworm, PokemonProfiles.tandemaus,
        PokemonProfiles.maushold, PokemonProfiles.familyOfThreeMaushold, PokemonProfiles.cetoddle, PokemonProfiles.cetitan,
        PokemonProfiles.frigibax, PokemonProfiles.arctibax, PokemonProfiles.baxcalibur, PokemonProfiles.tatsugiri,
        PokemonProfiles.droopyTatsugiri, PokemonProfiles.stretchyTatsugiri, PokemonProfiles.cyclizar, PokemonProfiles.pawmi,
        PokemonProfiles.pawmo, PokemonProfiles.pawmot, PokemonProfiles.wattrel, PokemonProfiles.kilowattrel,
        PokemonProfiles.bombirdier, PokemonProfiles.squawkabilly, PokemonProfiles.bluePlumageSquawkabilly, PokemonProfiles.yellowPlumageSquawkabilly,
        PokemonProfiles.whitePlumageSquawkabilly, PokemonProfiles.flamigo, PokemonProfiles.klawf, PokemonProfiles.nacli,
        PokemonProfiles.naclstack, PokemonProfiles.garganacl, PokemonProfiles.glimmet, PokemonProfiles.glimmora,
        PokemonProfiles.megaGlimmora, PokemonProfiles.shroodle, PokemonProfiles.grafaiai, PokemonProfiles.fidough,
        PokemonProfiles.dachsbun, PokemonProfiles.maschiff, PokemonProfiles.mabosstiff, PokemonProfiles.bramblin,
        PokemonProfiles.brambleghast, PokemonProfiles.gimmighoul, PokemonProfiles.roamingGimmighoul, PokemonProfiles.gholdengo,
        PokemonProfiles.greatTusk, PokemonProfiles.bruteBonnet, PokemonProfiles.sandyShocks, PokemonProfiles.screamTail,
        PokemonProfiles.flutterMane, PokemonProfiles.slitherWing, PokemonProfiles.roaringMoon, PokemonProfiles.ironTreads,
        PokemonProfiles.ironMoth, PokemonProfiles.ironHands, PokemonProfiles.ironJugulis, PokemonProfiles.ironThorns,
        PokemonProfiles.ironBundle, PokemonProfiles.ironValiant, PokemonProfiles.tingLu, PokemonProfiles.chienPao,
        PokemonProfiles.woChien, PokemonProfiles.chiYu, PokemonProfiles.koraidon, PokemonProfiles.limitedBuildKoraidon,
        PokemonProfiles.sprintingBuildKoraidon, PokemonProfiles.swimmingBuildKoraidon, PokemonProfiles.glidingBuildKoraidon, PokemonProfiles.miraidon,
        PokemonProfiles.lowPowerModeMiraidon, PokemonProfiles.driveModeMiraidon, PokemonProfiles.aquaticModeMiraidon, PokemonProfiles.glideModeMiraidon,
        PokemonProfiles.tinkatink, PokemonProfiles.tinkatuff, PokemonProfiles.tinkaton, PokemonProfiles.charcadet,
        PokemonProfiles.armarouge, PokemonProfiles.ceruledge, PokemonProfiles.toedscool, PokemonProfiles.toedscruel,
        PokemonProfiles.kingambit, PokemonProfiles.clodsire, PokemonProfiles.annihilape, PokemonProfiles.walkingWake,
        PokemonProfiles.ironLeaves, PokemonProfiles.dipplin, PokemonProfiles.poltchageist, PokemonProfiles.artisanPoltchageist,
        PokemonProfiles.sinistcha, PokemonProfiles.masterpieceSinistcha, PokemonProfiles.okidogi, PokemonProfiles.munkidori,
        PokemonProfiles.fezandipiti, PokemonProfiles.ogerpon, PokemonProfiles.wellspringMaskOgerpon, PokemonProfiles.hearthflameMaskOgerpon,
        PokemonProfiles.cornerstoneMaskOgerpon, PokemonProfiles.archaludon, PokemonProfiles.hydrapple, PokemonProfiles.gougingFire,
        PokemonProfiles.ragingBolt, PokemonProfiles.ironBoulder, PokemonProfiles.ironCrown, PokemonProfiles.terapagos,
        PokemonProfiles.terastalTerapagos, PokemonProfiles.stellarTerapagos, PokemonProfiles.pecharunt,
    ]
}
