enum Gen05PokemonProfiles {
    static let all: [PokemonProfile] = [
        PokemonProfiles.victini, PokemonProfiles.snivy, PokemonProfiles.servine, PokemonProfiles.serperior,
        PokemonProfiles.tepig, PokemonProfiles.pignite, PokemonProfiles.emboar, PokemonProfiles.megaEmboar,
        PokemonProfiles.oshawott, PokemonProfiles.dewott, PokemonProfiles.samurott, PokemonProfiles.hisuiSamurott,
        PokemonProfiles.patrat, PokemonProfiles.watchog, PokemonProfiles.lillipup, PokemonProfiles.herdier,
        PokemonProfiles.stoutland, PokemonProfiles.purrloin, PokemonProfiles.liepard, PokemonProfiles.pansage,
        PokemonProfiles.simisage, PokemonProfiles.pansear, PokemonProfiles.simisear, PokemonProfiles.panpour,
        PokemonProfiles.simipour, PokemonProfiles.munna, PokemonProfiles.musharna, PokemonProfiles.pidove,
        PokemonProfiles.tranquill, PokemonProfiles.unfezant, PokemonProfiles.blitzle, PokemonProfiles.zebstrika,
        PokemonProfiles.roggenrola, PokemonProfiles.boldore, PokemonProfiles.gigalith, PokemonProfiles.woobat,
        PokemonProfiles.swoobat, PokemonProfiles.drilbur, PokemonProfiles.excadrill, PokemonProfiles.megaExcadrill,
        PokemonProfiles.audino, PokemonProfiles.megaAudino, PokemonProfiles.timburr, PokemonProfiles.gurdurr,
        PokemonProfiles.conkeldurr, PokemonProfiles.tympole, PokemonProfiles.palpitoad, PokemonProfiles.seismitoad,
        PokemonProfiles.throh, PokemonProfiles.sawk, PokemonProfiles.sewaddle, PokemonProfiles.swadloon,
        PokemonProfiles.leavanny, PokemonProfiles.venipede, PokemonProfiles.whirlipede, PokemonProfiles.scolipede,
        PokemonProfiles.cottonee, PokemonProfiles.whimsicott, PokemonProfiles.petilil, PokemonProfiles.lilligant,
        PokemonProfiles.hisuiLilligant, PokemonProfiles.basculin, PokemonProfiles.blueStripedBasculin, PokemonProfiles.whiteStripedBasculin,
        PokemonProfiles.sandile, PokemonProfiles.krokorok, PokemonProfiles.krookodile, PokemonProfiles.darumaka,
        PokemonProfiles.galarDarumaka, PokemonProfiles.darmanitan, PokemonProfiles.zenDarmanitan, PokemonProfiles.galarStandardDarmanitan,
        PokemonProfiles.galarZenDarmanitan, PokemonProfiles.maractus, PokemonProfiles.dwebble, PokemonProfiles.crustle,
        PokemonProfiles.scraggy, PokemonProfiles.scrafty, PokemonProfiles.sigilyph, PokemonProfiles.yamask,
        PokemonProfiles.galarYamask, PokemonProfiles.cofagrigus, PokemonProfiles.tirtouga, PokemonProfiles.carracosta,
        PokemonProfiles.archen, PokemonProfiles.archeops, PokemonProfiles.trubbish, PokemonProfiles.garbodor,
        PokemonProfiles.gmaxGarbodor, PokemonProfiles.zorua, PokemonProfiles.hisuiZorua, PokemonProfiles.zoroark,
        PokemonProfiles.hisuiZoroark, PokemonProfiles.minccino, PokemonProfiles.cinccino, PokemonProfiles.gothita,
        PokemonProfiles.gothorita, PokemonProfiles.gothitelle, PokemonProfiles.solosis, PokemonProfiles.duosion,
        PokemonProfiles.reuniclus, PokemonProfiles.ducklett, PokemonProfiles.swanna, PokemonProfiles.vanillite,
        PokemonProfiles.vanillish, PokemonProfiles.vanilluxe, PokemonProfiles.deerling, PokemonProfiles.summerDeerling,
        PokemonProfiles.autumnDeerling, PokemonProfiles.winterDeerling, PokemonProfiles.sawsbuck, PokemonProfiles.summerSawsbuck,
        PokemonProfiles.autumnSawsbuck, PokemonProfiles.winterSawsbuck, PokemonProfiles.emolga, PokemonProfiles.karrablast,
        PokemonProfiles.escavalier, PokemonProfiles.foongus, PokemonProfiles.amoonguss, PokemonProfiles.frillish,
        PokemonProfiles.femaleFrillish, PokemonProfiles.jellicent, PokemonProfiles.femaleJellicent, PokemonProfiles.alomomola,
        PokemonProfiles.joltik, PokemonProfiles.galvantula, PokemonProfiles.ferroseed, PokemonProfiles.ferrothorn,
        PokemonProfiles.klink, PokemonProfiles.klang, PokemonProfiles.klinklang, PokemonProfiles.tynamo,
        PokemonProfiles.eelektrik, PokemonProfiles.eelektross, PokemonProfiles.elgyem, PokemonProfiles.beheeyem,
        PokemonProfiles.litwick, PokemonProfiles.lampent, PokemonProfiles.chandelure, PokemonProfiles.megaChandelure,
        PokemonProfiles.axew, PokemonProfiles.fraxure, PokemonProfiles.haxorus, PokemonProfiles.cubchoo,
        PokemonProfiles.beartic, PokemonProfiles.cryogonal, PokemonProfiles.shelmet, PokemonProfiles.accelgor,
        PokemonProfiles.stunfisk, PokemonProfiles.galarStunfisk, PokemonProfiles.mienfoo, PokemonProfiles.mienshao,
        PokemonProfiles.druddigon, PokemonProfiles.golett, PokemonProfiles.golurk, PokemonProfiles.megaGolurk,
        PokemonProfiles.pawniard, PokemonProfiles.bisharp, PokemonProfiles.bouffalant, PokemonProfiles.rufflet,
        PokemonProfiles.braviary, PokemonProfiles.hisuiBraviary, PokemonProfiles.vullaby, PokemonProfiles.mandibuzz,
        PokemonProfiles.heatmor, PokemonProfiles.durant, PokemonProfiles.deino, PokemonProfiles.zweilous,
        PokemonProfiles.hydreigon, PokemonProfiles.larvesta, PokemonProfiles.volcarona, PokemonProfiles.cobalion,
        PokemonProfiles.terrakion, PokemonProfiles.virizion, PokemonProfiles.tornadus, PokemonProfiles.therianTornadus,
        PokemonProfiles.thundurus, PokemonProfiles.therianThundurus, PokemonProfiles.reshiram, PokemonProfiles.zekrom,
        PokemonProfiles.landorus, PokemonProfiles.therianLandorus, PokemonProfiles.kyurem, PokemonProfiles.whiteKyurem,
        PokemonProfiles.blackKyurem, PokemonProfiles.keldeo, PokemonProfiles.resoluteKeldeo, PokemonProfiles.meloetta,
        PokemonProfiles.pirouetteMeloetta, PokemonProfiles.genesect, PokemonProfiles.douseGenesect, PokemonProfiles.shockGenesect,
        PokemonProfiles.burnGenesect, PokemonProfiles.chillGenesect,
    ]
}
