enum Gen03PokemonProfiles {
    static let all: [PokemonProfile] = [
        PokemonProfiles.azurill, PokemonProfiles.wynaut, PokemonProfiles.treecko, PokemonProfiles.grovyle,
        PokemonProfiles.sceptile, PokemonProfiles.megaSceptile, PokemonProfiles.torchic, PokemonProfiles.combusken,
        PokemonProfiles.blaziken, PokemonProfiles.megaBlaziken, PokemonProfiles.mudkip, PokemonProfiles.marshtomp,
        PokemonProfiles.swampert, PokemonProfiles.megaSwampert, PokemonProfiles.poochyena, PokemonProfiles.mightyena,
        PokemonProfiles.zigzagoon, PokemonProfiles.galarZigzagoon, PokemonProfiles.linoone, PokemonProfiles.galarLinoone,
        PokemonProfiles.wurmple, PokemonProfiles.silcoon, PokemonProfiles.beautifly, PokemonProfiles.cascoon,
        PokemonProfiles.dustox, PokemonProfiles.lotad, PokemonProfiles.lombre, PokemonProfiles.ludicolo,
        PokemonProfiles.seedot, PokemonProfiles.nuzleaf, PokemonProfiles.shiftry, PokemonProfiles.taillow,
        PokemonProfiles.swellow, PokemonProfiles.wingull, PokemonProfiles.pelipper, PokemonProfiles.ralts,
        PokemonProfiles.kirlia, PokemonProfiles.gardevoir, PokemonProfiles.megaGardevoir, PokemonProfiles.surskit,
        PokemonProfiles.masquerain, PokemonProfiles.shroomish, PokemonProfiles.breloom, PokemonProfiles.slakoth,
        PokemonProfiles.vigoroth, PokemonProfiles.slaking, PokemonProfiles.nincada, PokemonProfiles.ninjask,
        PokemonProfiles.shedinja, PokemonProfiles.whismur, PokemonProfiles.loudred, PokemonProfiles.exploud,
        PokemonProfiles.makuhita, PokemonProfiles.hariyama, PokemonProfiles.nosepass, PokemonProfiles.skitty,
        PokemonProfiles.delcatty, PokemonProfiles.sableye, PokemonProfiles.megaSableye, PokemonProfiles.mawile,
        PokemonProfiles.megaMawile, PokemonProfiles.aron, PokemonProfiles.lairon, PokemonProfiles.aggron,
        PokemonProfiles.megaAggron, PokemonProfiles.meditite, PokemonProfiles.medicham, PokemonProfiles.megaMedicham,
        PokemonProfiles.electrike, PokemonProfiles.manectric, PokemonProfiles.megaManectric, PokemonProfiles.plusle,
        PokemonProfiles.minun, PokemonProfiles.volbeat, PokemonProfiles.illumise, PokemonProfiles.roselia,
        PokemonProfiles.gulpin, PokemonProfiles.swalot, PokemonProfiles.carvanha, PokemonProfiles.sharpedo,
        PokemonProfiles.megaSharpedo, PokemonProfiles.wailmer, PokemonProfiles.wailord, PokemonProfiles.numel,
        PokemonProfiles.camerupt, PokemonProfiles.megaCamerupt, PokemonProfiles.torkoal, PokemonProfiles.spoink,
        PokemonProfiles.grumpig, PokemonProfiles.spinda, PokemonProfiles.trapinch, PokemonProfiles.vibrava,
        PokemonProfiles.flygon, PokemonProfiles.cacnea, PokemonProfiles.cacturne, PokemonProfiles.swablu,
        PokemonProfiles.altaria, PokemonProfiles.megaAltaria, PokemonProfiles.zangoose, PokemonProfiles.seviper,
        PokemonProfiles.lunatone, PokemonProfiles.solrock, PokemonProfiles.barboach, PokemonProfiles.whiscash,
        PokemonProfiles.corphish, PokemonProfiles.crawdaunt, PokemonProfiles.baltoy, PokemonProfiles.claydol,
        PokemonProfiles.lileep, PokemonProfiles.cradily, PokemonProfiles.anorith, PokemonProfiles.armaldo,
        PokemonProfiles.feebas, PokemonProfiles.milotic, PokemonProfiles.castform, PokemonProfiles.sunnyCastform,
        PokemonProfiles.rainyCastform, PokemonProfiles.snowyCastform, PokemonProfiles.kecleon, PokemonProfiles.shuppet,
        PokemonProfiles.banette, PokemonProfiles.megaBanette, PokemonProfiles.duskull, PokemonProfiles.dusclops,
        PokemonProfiles.tropius, PokemonProfiles.chimecho, PokemonProfiles.megaChimecho, PokemonProfiles.absol,
        PokemonProfiles.megaAbsol, PokemonProfiles.snorunt, PokemonProfiles.glalie, PokemonProfiles.megaGlalie,
        PokemonProfiles.spheal, PokemonProfiles.sealeo, PokemonProfiles.walrein, PokemonProfiles.clamperl,
        PokemonProfiles.huntail, PokemonProfiles.gorebyss, PokemonProfiles.relicanth, PokemonProfiles.luvdisc,
        PokemonProfiles.bagon, PokemonProfiles.shelgon, PokemonProfiles.salamence, PokemonProfiles.megaSalamence,
        PokemonProfiles.beldum, PokemonProfiles.metang, PokemonProfiles.metagross, PokemonProfiles.megaMetagross,
        PokemonProfiles.regirock, PokemonProfiles.regice, PokemonProfiles.registeel, PokemonProfiles.latias,
        PokemonProfiles.megaLatias, PokemonProfiles.latios, PokemonProfiles.megaLatios, PokemonProfiles.kyogre,
        PokemonProfiles.primalKyogre, PokemonProfiles.groudon, PokemonProfiles.primalGroudon, PokemonProfiles.rayquaza,
        PokemonProfiles.megaRayquaza, PokemonProfiles.jirachi, PokemonProfiles.deoxys, PokemonProfiles.attackDeoxys,
        PokemonProfiles.defenseDeoxys, PokemonProfiles.speedDeoxys,
    ]
}
