enum Gen07PokemonProfiles {
    static let all: [PokemonProfile] = [
        PokemonProfiles.rowlet, PokemonProfiles.dartrix, PokemonProfiles.decidueye, PokemonProfiles.hisuiDecidueye,
        PokemonProfiles.litten, PokemonProfiles.torracat, PokemonProfiles.incineroar, PokemonProfiles.popplio,
        PokemonProfiles.brionne, PokemonProfiles.primarina, PokemonProfiles.pikipek, PokemonProfiles.trumbeak,
        PokemonProfiles.toucannon, PokemonProfiles.yungoos, PokemonProfiles.gumshoos, PokemonProfiles.totemGumshoos,
        PokemonProfiles.grubbin, PokemonProfiles.charjabug, PokemonProfiles.vikavolt, PokemonProfiles.totemVikavolt,
        PokemonProfiles.crabrawler, PokemonProfiles.crabominable, PokemonProfiles.megaCrabominable, PokemonProfiles.oricorio,
        PokemonProfiles.pomPomOricorio, PokemonProfiles.pauOricorio, PokemonProfiles.sensuOricorio, PokemonProfiles.cutiefly,
        PokemonProfiles.ribombee, PokemonProfiles.totemRibombee, PokemonProfiles.rockruff, PokemonProfiles.ownTempoRockruff,
        PokemonProfiles.lycanroc, PokemonProfiles.midnightLycanroc, PokemonProfiles.duskLycanroc, PokemonProfiles.wishiwashi,
        PokemonProfiles.schoolWishiwashi, PokemonProfiles.mareanie, PokemonProfiles.toxapex, PokemonProfiles.mudbray,
        PokemonProfiles.mudsdale, PokemonProfiles.dewpider, PokemonProfiles.araquanid, PokemonProfiles.totemAraquanid,
        PokemonProfiles.fomantis, PokemonProfiles.lurantis, PokemonProfiles.totemLurantis, PokemonProfiles.morelull,
        PokemonProfiles.shiinotic, PokemonProfiles.salandit, PokemonProfiles.salazzle, PokemonProfiles.totemSalazzle,
        PokemonProfiles.stufful, PokemonProfiles.bewear, PokemonProfiles.bounsweet, PokemonProfiles.steenee,
        PokemonProfiles.tsareena, PokemonProfiles.comfey, PokemonProfiles.oranguru, PokemonProfiles.passimian,
        PokemonProfiles.wimpod, PokemonProfiles.golisopod, PokemonProfiles.sandygast, PokemonProfiles.palossand,
        PokemonProfiles.pyukumuku, PokemonProfiles.typeNull, PokemonProfiles.silvally, PokemonProfiles.fightingSilvally,
        PokemonProfiles.flyingSilvally, PokemonProfiles.poisonSilvally, PokemonProfiles.groundSilvally, PokemonProfiles.rockSilvally,
        PokemonProfiles.bugSilvally, PokemonProfiles.ghostSilvally, PokemonProfiles.steelSilvally, PokemonProfiles.fireSilvally,
        PokemonProfiles.waterSilvally, PokemonProfiles.grassSilvally, PokemonProfiles.electricSilvally, PokemonProfiles.psychicSilvally,
        PokemonProfiles.iceSilvally, PokemonProfiles.dragonSilvally, PokemonProfiles.darkSilvally, PokemonProfiles.fairySilvally,
        PokemonProfiles.minior, PokemonProfiles.orangeMeteorMinior, PokemonProfiles.yellowMeteorMinior, PokemonProfiles.greenMeteorMinior,
        PokemonProfiles.blueMeteorMinior, PokemonProfiles.indigoMeteorMinior, PokemonProfiles.violetMeteorMinior, PokemonProfiles.redMinior,
        PokemonProfiles.orangeMinior, PokemonProfiles.yellowMinior, PokemonProfiles.greenMinior, PokemonProfiles.blueMinior,
        PokemonProfiles.indigoMinior, PokemonProfiles.violetMinior, PokemonProfiles.komala, PokemonProfiles.turtonator,
        PokemonProfiles.togedemaru, PokemonProfiles.totemTogedemaru, PokemonProfiles.mimikyu, PokemonProfiles.bustedMimikyu,
        PokemonProfiles.totemDisguisedMimikyu, PokemonProfiles.totemBustedMimikyu, PokemonProfiles.bruxish, PokemonProfiles.drampa,
        PokemonProfiles.megaDrampa, PokemonProfiles.dhelmise, PokemonProfiles.jangmoO, PokemonProfiles.hakamoO,
        PokemonProfiles.kommoO, PokemonProfiles.totemKommoO, PokemonProfiles.tapuKoko, PokemonProfiles.tapuLele,
        PokemonProfiles.tapuBulu, PokemonProfiles.tapuFini, PokemonProfiles.cosmog, PokemonProfiles.cosmoem,
        PokemonProfiles.solgaleo, PokemonProfiles.lunala, PokemonProfiles.nihilego, PokemonProfiles.buzzwole,
        PokemonProfiles.pheromosa, PokemonProfiles.xurkitree, PokemonProfiles.celesteela, PokemonProfiles.kartana,
        PokemonProfiles.guzzlord, PokemonProfiles.necrozma, PokemonProfiles.duskNecrozma, PokemonProfiles.dawnNecrozma,
        PokemonProfiles.ultraNecrozma, PokemonProfiles.magearna, PokemonProfiles.originalMagearna, PokemonProfiles.marshadow,
        PokemonProfiles.poipole, PokemonProfiles.naganadel, PokemonProfiles.stakataka, PokemonProfiles.blacephalon,
        PokemonProfiles.zeraora, PokemonProfiles.meltan, PokemonProfiles.melmetal, PokemonProfiles.gmaxMelmetal,
    ]
}
