enum Gen04PokemonProfiles {
    static let all: [PokemonProfile] = [
        PokemonProfiles.magnezone, PokemonProfiles.lickilicky, PokemonProfiles.rhyperior, PokemonProfiles.happiny,
        PokemonProfiles.tangrowth, PokemonProfiles.mimeJr, PokemonProfiles.electivire, PokemonProfiles.magmortar,
        PokemonProfiles.leafeon, PokemonProfiles.glaceon, PokemonProfiles.porygonZ, PokemonProfiles.munchlax,
        PokemonProfiles.togekiss, PokemonProfiles.bonsly, PokemonProfiles.ambipom, PokemonProfiles.yanmega,
        PokemonProfiles.honchkrow, PokemonProfiles.mismagius, PokemonProfiles.gliscor, PokemonProfiles.weavile,
        PokemonProfiles.mamoswine, PokemonProfiles.mantyke, PokemonProfiles.gallade, PokemonProfiles.megaGallade,
        PokemonProfiles.probopass, PokemonProfiles.budew, PokemonProfiles.roserade, PokemonProfiles.dusknoir,
        PokemonProfiles.chingling, PokemonProfiles.froslass, PokemonProfiles.megaFroslass, PokemonProfiles.turtwig,
        PokemonProfiles.grotle, PokemonProfiles.torterra, PokemonProfiles.chimchar, PokemonProfiles.monferno,
        PokemonProfiles.infernape, PokemonProfiles.piplup, PokemonProfiles.prinplup, PokemonProfiles.empoleon,
        PokemonProfiles.starly, PokemonProfiles.staravia, PokemonProfiles.staraptor, PokemonProfiles.bidoof,
        PokemonProfiles.bibarel, PokemonProfiles.kricketot, PokemonProfiles.kricketune, PokemonProfiles.shinx,
        PokemonProfiles.luxio, PokemonProfiles.luxray, PokemonProfiles.cranidos, PokemonProfiles.rampardos,
        PokemonProfiles.shieldon, PokemonProfiles.bastiodon, PokemonProfiles.burmy, PokemonProfiles.sandyBurmy,
        PokemonProfiles.trashBurmy, PokemonProfiles.wormadam, PokemonProfiles.sandyWormadam, PokemonProfiles.trashWormadam,
        PokemonProfiles.mothim, PokemonProfiles.sandyMothim, PokemonProfiles.trashMothim, PokemonProfiles.combee,
        PokemonProfiles.vespiquen, PokemonProfiles.pachirisu, PokemonProfiles.buizel, PokemonProfiles.floatzel,
        PokemonProfiles.cherubi, PokemonProfiles.cherrim, PokemonProfiles.sunshineCherrim, PokemonProfiles.shellos,
        PokemonProfiles.eastShellos, PokemonProfiles.gastrodon, PokemonProfiles.eastGastrodon, PokemonProfiles.drifloon,
        PokemonProfiles.drifblim, PokemonProfiles.buneary, PokemonProfiles.lopunny, PokemonProfiles.megaLopunny,
        PokemonProfiles.glameow, PokemonProfiles.purugly, PokemonProfiles.stunky, PokemonProfiles.skuntank,
        PokemonProfiles.bronzor, PokemonProfiles.bronzong, PokemonProfiles.chatot, PokemonProfiles.spiritomb,
        PokemonProfiles.gible, PokemonProfiles.gabite, PokemonProfiles.garchomp, PokemonProfiles.megaGarchomp,
        PokemonProfiles.riolu, PokemonProfiles.lucario, PokemonProfiles.megaLucario, PokemonProfiles.hippopotas,
        PokemonProfiles.hippowdon, PokemonProfiles.skorupi, PokemonProfiles.drapion, PokemonProfiles.croagunk,
        PokemonProfiles.toxicroak, PokemonProfiles.carnivine, PokemonProfiles.finneon, PokemonProfiles.lumineon,
        PokemonProfiles.snover, PokemonProfiles.abomasnow, PokemonProfiles.megaAbomasnow, PokemonProfiles.rotom,
        PokemonProfiles.heatRotom, PokemonProfiles.washRotom, PokemonProfiles.frostRotom, PokemonProfiles.fanRotom,
        PokemonProfiles.mowRotom, PokemonProfiles.uxie, PokemonProfiles.mesprit, PokemonProfiles.azelf,
        PokemonProfiles.dialga, PokemonProfiles.originDialga, PokemonProfiles.palkia, PokemonProfiles.originPalkia,
        PokemonProfiles.heatran, PokemonProfiles.regigigas, PokemonProfiles.giratina, PokemonProfiles.originGiratina,
        PokemonProfiles.cresselia, PokemonProfiles.phione, PokemonProfiles.manaphy, PokemonProfiles.darkrai,
        PokemonProfiles.shaymin, PokemonProfiles.skyShaymin, PokemonProfiles.arceus, PokemonProfiles.fightingArceus,
        PokemonProfiles.flyingArceus, PokemonProfiles.poisonArceus, PokemonProfiles.groundArceus, PokemonProfiles.rockArceus,
        PokemonProfiles.bugArceus, PokemonProfiles.ghostArceus, PokemonProfiles.steelArceus, PokemonProfiles.fireArceus,
        PokemonProfiles.waterArceus, PokemonProfiles.grassArceus, PokemonProfiles.electricArceus, PokemonProfiles.psychicArceus,
        PokemonProfiles.iceArceus, PokemonProfiles.dragonArceus, PokemonProfiles.darkArceus, PokemonProfiles.fairyArceus,
        PokemonProfiles.unknownArceus,
    ]
}
