enum Gen06PokemonProfiles {
    static let all: [PokemonProfile] = [
        PokemonProfiles.sylveon, PokemonProfiles.chespin, PokemonProfiles.quilladin, PokemonProfiles.chesnaught,
        PokemonProfiles.megaChesnaught, PokemonProfiles.fennekin, PokemonProfiles.braixen, PokemonProfiles.delphox,
        PokemonProfiles.megaDelphox, PokemonProfiles.froakie, PokemonProfiles.frogadier, PokemonProfiles.greninja,
        PokemonProfiles.battleBondGreninja, PokemonProfiles.ashGreninja, PokemonProfiles.megaGreninja, PokemonProfiles.bunnelby,
        PokemonProfiles.diggersby, PokemonProfiles.fletchling, PokemonProfiles.fletchinder, PokemonProfiles.talonflame,
        PokemonProfiles.scatterbug, PokemonProfiles.polarScatterbug, PokemonProfiles.tundraScatterbug, PokemonProfiles.continentalScatterbug,
        PokemonProfiles.gardenScatterbug, PokemonProfiles.elegantScatterbug, PokemonProfiles.meadowScatterbug, PokemonProfiles.modernScatterbug,
        PokemonProfiles.marineScatterbug, PokemonProfiles.archipelagoScatterbug, PokemonProfiles.highPlainsScatterbug, PokemonProfiles.sandstormScatterbug,
        PokemonProfiles.riverScatterbug, PokemonProfiles.monsoonScatterbug, PokemonProfiles.savannaScatterbug, PokemonProfiles.sunScatterbug,
        PokemonProfiles.oceanScatterbug, PokemonProfiles.jungleScatterbug, PokemonProfiles.fancyScatterbug, PokemonProfiles.pokeBallScatterbug,
        PokemonProfiles.spewpa, PokemonProfiles.polarSpewpa, PokemonProfiles.tundraSpewpa, PokemonProfiles.continentalSpewpa,
        PokemonProfiles.gardenSpewpa, PokemonProfiles.elegantSpewpa, PokemonProfiles.meadowSpewpa, PokemonProfiles.modernSpewpa,
        PokemonProfiles.marineSpewpa, PokemonProfiles.archipelagoSpewpa, PokemonProfiles.highPlainsSpewpa, PokemonProfiles.sandstormSpewpa,
        PokemonProfiles.riverSpewpa, PokemonProfiles.monsoonSpewpa, PokemonProfiles.savannaSpewpa, PokemonProfiles.sunSpewpa,
        PokemonProfiles.oceanSpewpa, PokemonProfiles.jungleSpewpa, PokemonProfiles.fancySpewpa, PokemonProfiles.pokeBallSpewpa,
        PokemonProfiles.vivillon, PokemonProfiles.icySnowVivillon, PokemonProfiles.polarVivillon, PokemonProfiles.tundraVivillon,
        PokemonProfiles.continentalVivillon, PokemonProfiles.gardenVivillon, PokemonProfiles.elegantVivillon, PokemonProfiles.modernVivillon,
        PokemonProfiles.marineVivillon, PokemonProfiles.archipelagoVivillon, PokemonProfiles.highPlainsVivillon, PokemonProfiles.sandstormVivillon,
        PokemonProfiles.riverVivillon, PokemonProfiles.monsoonVivillon, PokemonProfiles.savannaVivillon, PokemonProfiles.sunVivillon,
        PokemonProfiles.oceanVivillon, PokemonProfiles.jungleVivillon, PokemonProfiles.fancyVivillon, PokemonProfiles.pokeBallVivillon,
        PokemonProfiles.litleo, PokemonProfiles.pyroar, PokemonProfiles.femalePyroar, PokemonProfiles.flabebe,
        PokemonProfiles.yellowFlabebe, PokemonProfiles.orangeFlabebe, PokemonProfiles.blueFlabebe, PokemonProfiles.whiteFlabebe,
        PokemonProfiles.floette, PokemonProfiles.yellowFloette, PokemonProfiles.orangeFloette, PokemonProfiles.blueFloette,
        PokemonProfiles.whiteFloette, PokemonProfiles.eternalFloette, PokemonProfiles.megaFloette, PokemonProfiles.florges,
        PokemonProfiles.yellowFlorges, PokemonProfiles.orangeFlorges, PokemonProfiles.blueFlorges, PokemonProfiles.whiteFlorges,
        PokemonProfiles.skiddo, PokemonProfiles.gogoat, PokemonProfiles.pancham, PokemonProfiles.pangoro,
        PokemonProfiles.furfrou, PokemonProfiles.heartFurfrou, PokemonProfiles.starFurfrou, PokemonProfiles.diamondFurfrou,
        PokemonProfiles.debutanteFurfrou, PokemonProfiles.matronFurfrou, PokemonProfiles.dandyFurfrou, PokemonProfiles.laReineFurfrou,
        PokemonProfiles.kabukiFurfrou, PokemonProfiles.pharaohFurfrou, PokemonProfiles.espurr, PokemonProfiles.meowstic,
        PokemonProfiles.femaleMeowstic, PokemonProfiles.megaMeowstic, PokemonProfiles.honedge, PokemonProfiles.doublade,
        PokemonProfiles.aegislash, PokemonProfiles.bladeAegislash, PokemonProfiles.spritzee, PokemonProfiles.aromatisse,
        PokemonProfiles.swirlix, PokemonProfiles.slurpuff, PokemonProfiles.inkay, PokemonProfiles.malamar,
        PokemonProfiles.binacle, PokemonProfiles.barbaracle, PokemonProfiles.skrelp, PokemonProfiles.dragalge,
        PokemonProfiles.clauncher, PokemonProfiles.clawitzer, PokemonProfiles.helioptile, PokemonProfiles.heliolisk,
        PokemonProfiles.tyrunt, PokemonProfiles.tyrantrum, PokemonProfiles.amaura, PokemonProfiles.aurorus,
        PokemonProfiles.hawlucha, PokemonProfiles.megaHawlucha, PokemonProfiles.dedenne, PokemonProfiles.carbink,
        PokemonProfiles.goomy, PokemonProfiles.sliggoo, PokemonProfiles.hisuiSliggoo, PokemonProfiles.goodra,
        PokemonProfiles.hisuiGoodra, PokemonProfiles.klefki, PokemonProfiles.phantump, PokemonProfiles.trevenant,
        PokemonProfiles.pumpkaboo, PokemonProfiles.smallPumpkaboo, PokemonProfiles.largePumpkaboo, PokemonProfiles.superPumpkaboo,
        PokemonProfiles.gourgeist, PokemonProfiles.smallGourgeist, PokemonProfiles.largeGourgeist, PokemonProfiles.superGourgeist,
        PokemonProfiles.bergmite, PokemonProfiles.avalugg, PokemonProfiles.hisuiAvalugg, PokemonProfiles.noibat,
        PokemonProfiles.noivern, PokemonProfiles.xerneas, PokemonProfiles.activeXerneas, PokemonProfiles.yveltal,
        PokemonProfiles.zygarde, PokemonProfiles.tenPercentZygarde, PokemonProfiles.tenPercentPowerConstructZygarde, PokemonProfiles.fiftyPercentPowerConstructZygarde,
        PokemonProfiles.completeZygarde, PokemonProfiles.diancie, PokemonProfiles.megaDiancie, PokemonProfiles.hoopa,
        PokemonProfiles.unboundHoopa, PokemonProfiles.volcanion,
    ]
}
