enum Gen02PokemonProfiles {
    static let all: [PokemonProfile] = [
        PokemonProfiles.pichu, PokemonProfiles.spikyEaredPichu, PokemonProfiles.cleffa, PokemonProfiles.igglybuff,
        PokemonProfiles.crobat, PokemonProfiles.bellossom, PokemonProfiles.politoed, PokemonProfiles.slowking,
        PokemonProfiles.galarSlowking, PokemonProfiles.steelix, PokemonProfiles.megaSteelix, PokemonProfiles.tyrogue,
        PokemonProfiles.hitmontop, PokemonProfiles.blissey, PokemonProfiles.kingdra, PokemonProfiles.scizor,
        PokemonProfiles.megaScizor, PokemonProfiles.smoochum, PokemonProfiles.elekid, PokemonProfiles.magby,
        PokemonProfiles.espeon, PokemonProfiles.umbreon, PokemonProfiles.porygon2, PokemonProfiles.chikorita,
        PokemonProfiles.bayleef, PokemonProfiles.meganium, PokemonProfiles.megaMeganium, PokemonProfiles.cyndaquil,
        PokemonProfiles.quilava, PokemonProfiles.typhlosion, PokemonProfiles.hisuiTyphlosion, PokemonProfiles.totodile,
        PokemonProfiles.croconaw, PokemonProfiles.feraligatr, PokemonProfiles.megaFeraligatr, PokemonProfiles.sentret,
        PokemonProfiles.furret, PokemonProfiles.hoothoot, PokemonProfiles.noctowl, PokemonProfiles.ledyba,
        PokemonProfiles.ledian, PokemonProfiles.spinarak, PokemonProfiles.ariados, PokemonProfiles.chinchou,
        PokemonProfiles.lanturn, PokemonProfiles.togepi, PokemonProfiles.togetic, PokemonProfiles.natu,
        PokemonProfiles.xatu, PokemonProfiles.mareep, PokemonProfiles.flaaffy, PokemonProfiles.ampharos,
        PokemonProfiles.megaAmpharos, PokemonProfiles.marill, PokemonProfiles.azumarill, PokemonProfiles.sudowoodo,
        PokemonProfiles.hoppip, PokemonProfiles.skiploom, PokemonProfiles.jumpluff, PokemonProfiles.aipom,
        PokemonProfiles.sunkern, PokemonProfiles.sunflora, PokemonProfiles.yanma, PokemonProfiles.wooper,
        PokemonProfiles.paldeaWooper, PokemonProfiles.quagsire, PokemonProfiles.murkrow, PokemonProfiles.misdreavus,
        PokemonProfiles.unown, PokemonProfiles.bUnown, PokemonProfiles.cUnown, PokemonProfiles.dUnown,
        PokemonProfiles.eUnown, PokemonProfiles.fUnown, PokemonProfiles.gUnown, PokemonProfiles.hUnown,
        PokemonProfiles.iUnown, PokemonProfiles.jUnown, PokemonProfiles.kUnown, PokemonProfiles.lUnown,
        PokemonProfiles.mUnown, PokemonProfiles.nUnown, PokemonProfiles.oUnown, PokemonProfiles.pUnown,
        PokemonProfiles.qUnown, PokemonProfiles.rUnown, PokemonProfiles.sUnown, PokemonProfiles.tUnown,
        PokemonProfiles.uUnown, PokemonProfiles.vUnown, PokemonProfiles.wUnown, PokemonProfiles.xUnown,
        PokemonProfiles.yUnown, PokemonProfiles.zUnown, PokemonProfiles.exclamationUnown, PokemonProfiles.questionUnown,
        PokemonProfiles.wobbuffet, PokemonProfiles.girafarig, PokemonProfiles.pineco, PokemonProfiles.forretress,
        PokemonProfiles.dunsparce, PokemonProfiles.gligar, PokemonProfiles.snubbull, PokemonProfiles.granbull,
        PokemonProfiles.qwilfish, PokemonProfiles.hisuiQwilfish, PokemonProfiles.shuckle, PokemonProfiles.heracross,
        PokemonProfiles.megaHeracross, PokemonProfiles.sneasel, PokemonProfiles.hisuiSneasel, PokemonProfiles.teddiursa,
        PokemonProfiles.ursaring, PokemonProfiles.slugma, PokemonProfiles.magcargo, PokemonProfiles.swinub,
        PokemonProfiles.piloswine, PokemonProfiles.corsola, PokemonProfiles.galarCorsola, PokemonProfiles.remoraid,
        PokemonProfiles.octillery, PokemonProfiles.delibird, PokemonProfiles.mantine, PokemonProfiles.skarmory,
        PokemonProfiles.megaSkarmory, PokemonProfiles.houndour, PokemonProfiles.houndoom, PokemonProfiles.megaHoundoom,
        PokemonProfiles.phanpy, PokemonProfiles.donphan, PokemonProfiles.stantler, PokemonProfiles.smeargle,
        PokemonProfiles.miltank, PokemonProfiles.raikou, PokemonProfiles.entei, PokemonProfiles.suicune,
        PokemonProfiles.larvitar, PokemonProfiles.pupitar, PokemonProfiles.tyranitar, PokemonProfiles.megaTyranitar,
        PokemonProfiles.lugia, PokemonProfiles.hoOh, PokemonProfiles.celebi,
    ]
}
